#!/bin/sh

set -e

create_sensu_user_group() {
    # create sensu group
    if ! getent group sensu >/dev/null; then
        pw groupadd sensu
    fi

    # create sensu user
    if ! getent passwd sensu >/dev/null; then
        pw adduser sensu -g sensu -d /nonexistent \
           -s /usr/sbin/nologin -c "Sensu Monitoring Framework"
    fi
}

chown_sensu_dirs() {
    chown -R sensu:sensu /usr/local/etc/sensu
    chown -R sensu:sensu /var/log/sensu
    chown -R sensu:sensu /opt/sensu/sv
    chown -R sensu:sensu /var/run/sensu
}

create_sensu_user_group
chown_sensu_dirs

exit 0
