#!/bin/bash

# chkconfig: 345 90 90
# description: Sensu monitoring framework dashboard

### BEGIN INIT INFO
# Provides:       sensu-dashboard
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Sensu monitoring framework dashboard
### END INIT INFO

/etc/init.d/sensu-service dashboard $1

exit $?
