#!/bin/bash

echo 'yanking packages ...'

debs=`find * -name "*.deb"`
for d in $debs; do
    package_cloud yank sensu/stable/any/any $d
done

rpms=`find * -name "*.rpm"`
for r in $rpms; do
    package_cloud yank sensu/stable/el/5 $r
    package_cloud yank sensu/stable/el/6 $r
done

echo 'done.'
