#!/bin/sh
# postinst script for sensu
#

set -e

# summary of how this script can be called and ordering:
#  http://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
#  http://www.proulx.com/~bob/debian/hints/DpkgScriptOrder

sensu_services="sensu-api sensu-client sensu-dashboard sensu-server"

purge_sensu_files() {
    if [ -d /var/log/sensu ]; then
        rm -r /var/log/sensu
    fi
    if [ -d /etc/sensu ]; then
        rm -r /etc/sensu
    fi
}

purge_sensu_services() {
    for service in $sensu_services; do
        update-rc.d $service remove >/dev/null || true
    done
}

purge_sensu_user_group() {
    if getent passwd sensu >/dev/null; then
        deluser sensu
    fi
    if getent group sensu >/dev/null; then
        delgroup sensu
    fi
}

case "$1" in
    purge)
        purge_sensu_files
        purge_sensu_services
        purge_sensu_user_group
    ;;

    remove|upgrade|abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
