#!/bin/sh
# prerm script for sensu
#

set -e

# summary of how this script can be called and ordering:
#  http://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
#  http://www.proulx.com/~bob/debian/hints/DpkgScriptOrder

sensu_services="sensu-client sensu-server sensu-api sensu-dashboard"

# try to stop any running sensu services (not all will be running)
stop_sensu_services() {
    for service in $sensu_services; do
        if [ -x "/etc/init.d/$service" ]; then
            if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d $service stop || true
            else
                /etc/init.d/$service stop || true
            fi
        fi
    done

    # send sensu-runsvdir a hup to stop itself and supervised services
    if [ -f "/etc/init/sensu-runsvdir.conf" ]; then
        reload sensu-runsvdir || pkill -HUP -f /opt/sensu/embedded/bin/runsvdir || true
    fi
    if [ -f "/etc/inittab" ]; then
        if grep -q sensu-runsvdir /etc/inittab; then
            sed "/sensu-runsvdir/d" /etc/inittab > /etc/inittab
            init q
            pkill -HUP -f /opt/sensu/embedded/bin/runsvdir || true
        fi
    fi
}

case "$1" in
    remove|purge)
        stop_sensu_services
        ;;

    upgrade|deconfigure)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
